/**
 * Error codes and error-related constants
 */

// =============================================================================
// ERROR CODES
// =============================================================================

export const ERROR_CODE = {
    // HTTP and request errors
    PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
    MISSING_CONTENT_TYPE: 'MISSING_CONTENT_TYPE',
    INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
    REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',

    // Validation errors
    INVALID_PAGE: 'INVALID_PAGE',
    INVALID_LIMIT: 'INVALID_LIMIT',
    INVALID_SORT_FORMAT: 'INVALID_SORT_FORMAT',
    SEARCH_TOO_SHORT: 'SEARCH_TOO_SHORT',
    SEARCH_TOO_LONG: 'SEARCH_TOO_LONG',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    VALIDATION_FAILED: 'VALIDATION_FAILED',

    // UUID validation errors
    MISSING_UUID: 'MISSING_UUID',
    EMPTY_UUID: 'EMPTY_UUID',
    INVALID_UUID: 'INVALID_UUID',

    // Integer validation errors
    MISSING_VALUE: 'MISSING_VALUE',
    EMPTY_VALUE: 'EMPTY_VALUE',
    INVALID_INTEGER: 'INVALID_INTEGER',
    NEGATIVE_NOT_ALLOWED: 'NEGATIVE_NOT_ALLOWED',
    VALUE_TOO_SMALL: 'VALUE_TOO_SMALL',
    VALUE_TOO_LARGE: 'VALUE_TOO_LARGE',

    // File validation errors
    TOO_MANY_FILES: 'TOO_MANY_FILES',
    INVALID_FILE_OBJECT: 'INVALID_FILE_OBJECT',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    MISSING_FILE_EXTENSION: 'MISSING_FILE_EXTENSION',
    INVALID_FILE_EXTENSION: 'INVALID_FILE_EXTENSION',

    // Circuit breaker errors
    CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',

    // HTTP status error codes
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
    CONFLICT: 'CONFLICT',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BAD_GATEWAY: 'BAD_GATEWAY',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;
